version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pine
      POSTGRES_PASSWORD: lsm0310
      POSTGRES_DB: todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
